// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace AutoDealer_API
{
    public partial class CarPriceModel
    {
        /// <summary>
        /// model input class for CarPriceModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"id")]
            public float Id { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"brand")]
            public string Brand { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"model")]
            public string Model { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"model_year")]
            public float Model_year { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"milage")]
            public float Milage { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"fuel_type")]
            public string Fuel_type { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"engine")]
            public string Engine { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"transmission")]
            public string Transmission { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"ext_col")]
            public string Ext_col { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"int_col")]
            public string Int_col { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"accident")]
            public string Accident { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"clean_title")]
            public string Clean_title { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for CarPriceModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"brand")]
            public float[] Brand { get; set; }

            [ColumnName(@"model")]
            public float[] Model { get; set; }

            [ColumnName(@"model_year")]
            public float Model_year { get; set; }

            [ColumnName(@"milage")]
            public float Milage { get; set; }

            [ColumnName(@"fuel_type")]
            public float[] Fuel_type { get; set; }

            [ColumnName(@"engine")]
            public float[] Engine { get; set; }

            [ColumnName(@"transmission")]
            public float[] Transmission { get; set; }

            [ColumnName(@"ext_col")]
            public float[] Ext_col { get; set; }

            [ColumnName(@"int_col")]
            public float[] Int_col { get; set; }

            [ColumnName(@"accident")]
            public float[] Accident { get; set; }

            [ColumnName(@"clean_title")]
            public float[] Clean_title { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("CarPriceModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
