// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML.Transforms;

namespace AutoDealer_API
{
    public partial class CarPriceModel
    {
        public const string RetrainFilePath =  @"C:\HDD\Facultate\An 1\Semestru 1\Covaci\Laboratoare\Project\train.csv";
        public const char RetrainSeparatorChar = ',';
        public const bool RetrainHasHeader =  true;
        public const bool RetrainAllowQuoting =  false;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader, bool allowQuoting = RetrainAllowQuoting)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader, allowQuoting);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader, bool allowQuoting)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader, allowQuoting: allowQuoting);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"accident", @"accident", outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"id", @"id"),new InputOutputColumnPair(@"model_year", @"model_year"),new InputOutputColumnPair(@"milage", @"milage")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"brand",outputColumnName:@"brand"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"model",outputColumnName:@"model"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"fuel_type",outputColumnName:@"fuel_type"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"engine",outputColumnName:@"engine"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"transmission",outputColumnName:@"transmission"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"ext_col",outputColumnName:@"ext_col"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"int_col",outputColumnName:@"int_col"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"clean_title",outputColumnName:@"clean_title"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"accident",@"id",@"model_year",@"milage",@"brand",@"model",@"fuel_type",@"engine",@"transmission",@"ext_col",@"int_col",@"clean_title"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=1225,NumberOfIterations=4,MinimumExampleCountPerLeaf=20,LearningRate=0.30840620155797854,LabelColumnName=@"price",FeatureColumnName=@"Features",Booster=new GradientBooster.Options(){SubsampleFraction=0.3224234699008072,FeatureFraction=0.99999999,L1Regularization=1.0033647599190106E-09,L2Regularization=0.9999997766729865},MaximumBinCountPerFeature=241}));

            return pipeline;
        }
    }
 }
